project_name: grafiport

builds:
  - env: [CGO_ENABLED=0]
dockers:
-
  goos: linux
  goarch: amd64
  dockerfile: goreleaser.dockerfile
  image_templates:
  - 'ghcr.io/telekom-mms/grafiport:{{ .Tag }}'
  - 'ghcr.io/telekom-mms/grafiport:latest'
